### ISSUE TITLE
The radix-ui HoverCard in the Factions tab appead behind the Modal Dialog for Units or Equipment

### ISSUE THREAD

**Issue by WolfangT** [Bob-The-Seagull-King/trenchcrusadecompendium#1]
When using the page from Firefox 128.0.3 on fedora linux, the HoverCards for Keywords appear behind the open modal dialog.

Adding
```css
div:has(> .HoverCardContent) {
    z-index: 9999999999 !important;
}
```
to `iconcomponents.scss` at line 214 should resolve the issue

Example image:
![Screenshot from 2024-08-08 00-49-02](https://github.com/user-attachments/assets/9aeb4990-4d8a-4aec-b64a-367cc393871e)
![Screenshot from 2024-08-08 00-42-34](https://github.com/user-attachments/assets/57f3f2e6-4aad-4742-877d-70345707b73f)
